---
name: Clean Image Registry - Test
on:
  workflow_dispatch:
    inputs:
      image_name:
        description: Image Name
        required: true
        type: string
      prod_keep_at_least:
        description: Minimum number of production images to retain after cut-off
        required: false
        type: number
        default: 5
      prod_cut_off:
        description: Cut-off for production images (format as supported by python's
          dateparser)
        required: false
        type: string
        default: One month ago UTC
      testing_keep_at_least:
        description: Minimum number of testing/staging images to retain after cut-off
        required: false
        type: number
        default: 2
      testing_cut_off:
        description: Cut-off for testing/staging images (format as supported by python's
          dateparser)
        required: false
        type: string
        default: One week ago UTC
      non_semver_keep_at_least:
        description: Cut-off for Non-Semver images (format as supported by python's
          dateparser)
        required: false
        type: number
        default: 2
      non_semver_cut_off:
        description: Cut-off for Non-SemVer images (format as supported by python's
          dateparser)
        required: false
        type: string
        default: One week ago UTC
      untagged_cut_off:
        description: Cut-off for Orphan images (format as supported by python's dateparser)
        required: false
        type: string
        default: One week ago UTC
    secrets:
      IMAGE_CLEANUP_TOKEN:
        description: Github token with permissions - read:packages, write:packages,
          delete-packages
        required: true
      MS_TEAMS_WEBHOOK_URI:
        description: |
          MS Teams Webhook URI that sends information to the corresponding Teams channel 
          Follow this link for creating Webhook URI:- https://tinyurl.com/yjertc35
        required: true
jobs:
  clean-ghcr-prod:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    steps:
      - name: Validating inputs for production
        run: |
          if [[ $(("${{ inputs.prod_keep_at_least }}")) -lt 5 ]]; then
              echo "Provided value of prod_keep_at_least cannot be less than 5"
              exit 1
          fi
      